### ISSUE TITLE
Some highlighted stuff is not highlighted in the theme

### ISSUE THREAD

**Issue by fazer2004** [witalihirsch/Mono-gtk-theme#35]
In some situations highlighted things are not highlighted in the theme. For example in the default PDF-viewer, if you search with Ctrl+F for a certain word, the program shows the page of the word, but doesn't highlight the word itself.
Another example is the shut down menu. With the default system theme I can see that the cancel-button is highlighted (if I press enter I cancel the shut down process). With the Mono-theme I can't see it:
![Adwaita](https://user-images.githubusercontent.com/112729784/216368905-6e6131ce-0fd0-45ec-a8f1-e17d3f5c2d49.png)
![Mono](https://user-images.githubusercontent.com/112729784/216368961-616b2b0c-853f-4478-8481-bf015cac20d7.png)

System information:
OS: Debian 11
Gnome-Version 3.38.5

**Comment by osieltorres** [comment]
Besides shutdown popup, it is also missing on the reboot and power off popup.

**Comment by witalihirsch** [comment]
fixed

**Comment by fazer2004** [comment]
Now the shut down button is red. The problem still is that the cancel button is highlighted from the system and if I press enter, the cancel-button is triggered.
